### ISSUE TITLE
the dimension on the shoulder gear is not correct

### ISSUE THREAD

**Issue by jakechung42** [pdx-robotics/Robot-Arm#14]
![image](https://user-images.githubusercontent.com/33278786/67452773-2b058080-f5d9-11e9-8a2f-5f6e0010ecd3.png)
Might need to re-dimension this gear.

**Comment by jakechung42** [comment]
Need to investigate why the shoulder gear is off. The solidworks model makes it seem like it's bigger, but it's actually smaller when printed. Possible printing error.

**Comment by VladislavRuchin** [comment]
I re-adjusted the dimensions of the shoulder and support gears by referring to the dimensions of the base.
