### ISSUE TITLE
SVG Transformation

### ISSUE THREAD

**Issue by JessicaHolm** [pdx-robotics/Robot-Arm#18]
We need to figure out how to transform a svg vector file into something that can causes the robot arm to move.

**Comment by anthonybob** [comment]
This problem has been solved. I wrote a python script to extract the paths out of an SVG file. I am currently adding more functionality so my script will recognize all the different commands in an svg path. For example, the 'c' tag in an svg path is a bezier curve. The tag is followed by four coordinates. We can calculate an arbitrary amount of points of the curve from those four points using a recursive function.
